name: pymol2jmolanimat-binderized
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyterlab>=1.0
  - jmol
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - seaborn
  - regex
  - pip
  - pip:
    - xvfbwrapper
    